services:
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: order-service
    environment: 
      - USER_SERVICE_URL=http://user-service:8081 
    depends_on: 
      - user-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge